#!/bin/bash
awk '
/app.get\("\/api\/admin\/partners"/ {
  print "  // ----- SOURCING INQUIRY API -----"
  print "  app.post(\"/api/public/sourcing\", async (req, res) => {"
  print "    try {"
  print "      const ticketId = \"SRC-\" + Math.random().toString(36).substr(2, 6).toUpperCase();"
  print "      const inquiry = await prisma.sourcingInquiry.create({"
  print "        data: { ...req.body, ticketId },"
  print "      });"
  print "      res.json(inquiry);"
  print "    } catch (error) {"
  print "      console.error(error);"
  print "      res.status(500).json({ error: \"Server error\" });"
  print "    }"
  print "  });"
  print ""
  print "  app.get(\"/api/admin/sourcing\", authMiddleware, async (req, res) => {"
  print "    try {"
  print "      const inquiries = await prisma.sourcingInquiry.findMany({"
  print "        orderBy: { createdAt: \"desc\" },"
  print "      });"
  print "      res.json(inquiries);"
  print "    } catch (error) {"
  print "      console.error(error);"
  print "      res.status(500).json({ error: \"Server error\" });"
  print "    }"
  print "  });"
  print ""
  print "  app.put(\"/api/admin/sourcing/:id\", authMiddleware, async (req, res) => {"
  print "    try {"
  print "      const inquiry = await prisma.sourcingInquiry.update({"
  print "        where: { id: req.params.id },"
  print "        data: req.body,"
  print "      });"
  print "      res.json(inquiry);"
  print "    } catch (error) {"
  print "      console.error(error);"
  print "      res.status(500).json({ error: \"Server error\" });"
  print "    }"
  print "  });"
  print ""
  print "  app.delete(\"/api/admin/sourcing/:id\", authMiddleware, async (req, res) => {"
  print "    try {"
  print "      await prisma.sourcingInquiry.delete({"
  print "        where: { id: req.params.id },"
  print "      });"
  print "      res.json({ success: true });"
  print "    } catch (error) {"
  print "      console.error(error);"
  print "      res.status(500).json({ error: \"Server error\" });"
  print "    }"
  print "  });"
  print ""
}
{print}
' server.app.ts > temp.ts && mv temp.ts server.app.ts
