#!/bin/bash
awk '
/app.get\("\/api\/admin\/applications"/ {
  print "  // ----- PARTNERS API -----"
  print "  app.get(\"/api/partners\", async (req, res) => {"
  print "    try {"
  print "      const partners = await prisma.partner.findMany({"
  print "        where: { isActive: true },"
  print "        orderBy: { order: \"asc\" },"
  print "      });"
  print "      res.json(partners);"
  print "    } catch (error) {"
  print "      console.error(error);"
  print "      res.status(500).json({ error: \"Server error\" });"
  print "    }"
  print "  });"
  print ""
  print "  app.get(\"/api/admin/partners\", authMiddleware, async (req, res) => {"
  print "    try {"
  print "      const partners = await prisma.partner.findMany({"
  print "        orderBy: { order: \"asc\" },"
  print "      });"
  print "      res.json(partners);"
  print "    } catch (error) {"
  print "      console.error(error);"
  print "      res.status(500).json({ error: \"Server error\" });"
  print "    }"
  print "  });"
  print ""
  print "  app.post(\"/api/admin/partners\", authMiddleware, async (req, res) => {"
  print "    try {"
  print "      const partner = await prisma.partner.create({"
  print "        data: req.body,"
  print "      });"
  print "      res.json(partner);"
  print "    } catch (error) {"
  print "      console.error(error);"
  print "      res.status(500).json({ error: \"Server error\" });"
  print "    }"
  print "  });"
  print ""
  print "  app.put(\"/api/admin/partners/:id\", authMiddleware, async (req, res) => {"
  print "    try {"
  print "      const partner = await prisma.partner.update({"
  print "        where: { id: req.params.id },"
  print "        data: req.body,"
  print "      });"
  print "      res.json(partner);"
  print "    } catch (error) {"
  print "      console.error(error);"
  print "      res.status(500).json({ error: \"Server error\" });"
  print "    }"
  print "  });"
  print ""
  print "  app.delete(\"/api/admin/partners/:id\", authMiddleware, async (req, res) => {"
  print "    try {"
  print "      await prisma.partner.delete({"
  print "        where: { id: req.params.id },"
  print "      });"
  print "      res.json({ success: true });"
  print "    } catch (error) {"
  print "      console.error(error);"
  print "      res.status(500).json({ error: \"Server error\" });"
  print "    }"
  print "  });"
  print ""
}
{print}
' server.app.ts > temp.ts && mv temp.ts server.app.ts
