import { prisma } from "./db.js";

export const INITIAL_BUSINESS_OPPORTUNITIES = [
  {
    slug: "basra-petrochem-hub",
    titleEn: "Basra Sovereign Petrochemical Complex & Associated Gas Valorization",
    titleAr: "مجمع البصرة السيادي للبتروكيماويات وتثمين الغاز المصاحب",
    titleZh: "巴士拉主权级石化联合体与油田伴生气深度利用项目",
    titleCkb: "کۆمەڵگەی پێترۆکیمیایی سیادی بەسرە و بەکارهێنانی گازی هاوپێچ",
    summaryEn: "A tier-one downstream refining and polymer production facility designed to capture flaring gas across southern fields, providing 10-year fiscal immunity under Investment Law No. 13.",
    summaryAr: "منشأة تحويلية وتكريرية لإنتاج البوليمرات مصممة لاستثمار الغاز المحروق في حقول الجنوب، مع إعفاء ضريبي لمدة ١٠ سنوات بموجب قانون الاستثمار رقم ١٣.",
    summaryZh: "伊拉克南部特大型下游精细化工与聚合物生产基地，旨在深度回收油田火炬放空天然气，享受第13号投资法全额10年免税优惠。",
    summaryCkb: "پرۆژەیەکی گەورەی پاڵاوتن و بەرهەمهێنانی پۆلیمەر بۆ سوودوەرگرتن لە گازی کێڵگەکانی باشوور، بە بەخشینی باج بۆ ١٠ ساڵ بەپێی یاسای وەبەرهێنان.",
    contentEn: "The Iraqi Ministry of Oil, in close bilateral coordination with Chinese petrochemical engineering consortiums, invites qualified industrial EPC partners for Phase II equity participation in the Basra Petrochemical Complex. The project integrates cryogenic separation units, ethylene crackers, and high-density polyethylene production. Sovereign guarantees include free allocation of 450 hectares in the Khor Al-Zubair Industrial Zone, zero customs tariff on imported engineering plant equipment, and full constitutional freedom to repatriate capital yields in RMB or USD.",
    contentAr: "تدعو وزارة النفط العراقية، بالتنسيق الثنائي الوثيق مع تحالفات الهندسة البتروكيماوية الصينية، الشركاء الصناعيين المؤهلين للمشاركة الرأسمالية في المرحلة الثانية من مجمع البصرة. يشمل المشروع وحدات الفصل التبريدي، وتكسير الإيثيلين، وإنتاج البولي إيثيلين. تتضمن الضمانات السيادية تخصيص ٤٥٠ هكتاراً في خور الزبير مع إعفاء جمركي كامل لجميع المعدات وحرية دستورية كاملة لتحويل الأرباح باليوان أو الدولار.",
    contentZh: "伊拉克石油部在中伊双边协调框架下，诚邀具备资质的国际工程与能源财团参与巴士拉大型石化基地第二阶段的股权合作。项目涵盖深冷分离装置、乙烯裂解炉及高密度聚乙烯生产线。伊拉克政府提供的主权保障包括：在祖拜尔工业特区免费划拨450公顷工业用地、工程总承包设备进口零关税、以及受宪法保护的投资收益人民币/美元全额自由汇出机制。",
    contentCkb: "وەزارەتی نەوتی عێراق بە هەماهەنگی لەگەڵ هاوپەیمانی کۆمپانیا ئەندازیارییە چینییەکان، داوا لە وەبەرهێنەران دەکات بۆ بەشداریکردن لە قۆناغی دووەمی مۆمەڵگەی پێترۆکیمیایی بەسرە. پڕۆژەکە تەرخانکردنی ٤٥٠ هێکتار زەوی و لێخۆشبوونی گومرگی و گواستنەوەی ئازادی قازانج لەخۆدەگرێت.",
    category: "ENERGY",
    sector: "Petrochemicals & Gas Capture",
    investmentValue: "$3.2 Billion",
    location: "Khor Al-Zubair, Basra",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    order: 1,
    status: "OPEN",
    contactEmail: "petrochem@iraqi-chineseagency.com"
  },
  {
    slug: "sino-iraq-solar-microgrid",
    titleEn: "Muthanna & Najaf 1.4GW Desert Photovoltaic Microgrid Corridor",
    titleAr: "ممر حقول الطاقة الشمسية الكهروضوئية في بادية المثنى والنجف بقوة 1.4 غيغاواط",
    titleZh: "穆萨纳与纳杰夫沙漠1.4吉瓦大型光伏微电网走廊",
    titleCkb: "کۆریدۆری وێستگەی سۆلاری دەشتی موسەننا و نەجەف بە توانای ١.٤ گێگاوات",
    summaryEn: "Utility-scale desert solar installations linked directly with provincial transmission nodes, offering guaranteed 25-year sovereign power purchase agreements (PPA).",
    summaryAr: "محطات طاقة شمسية كبرى في بادية الجنوب مرتبطة مباشرة بشبكة النقل الوطنية، مع اتفاقيات شراء طاقة سيادية مضمونة لمدة ٢٥ عاماً (PPA).",
    summaryZh: "位于伊拉克南部沙漠的大型并网光伏电站集群，直接接入国家主干电网，享有伊拉克电力部提供的25年期主权级照付不议购电协议（PPA）。",
    summaryCkb: "وێستگەی بەرهەمهێنانی کارەبای سۆلار لە دەشتاییەکانی باشوور، بەستراوەتەوە بە تۆڕی نیشتمانی بە گرێبەستی ٢٥ ساڵەی کڕینی وزە.",
    contentEn: "Designed to relieve southern grid deficits, this bilateral initiative covers two solar parks equipped with dual-axis trackers and 300MWh battery energy storage systems (BESS). Consortium members benefit from fast-track customs clearance at Safwan, exemption from corporate income tax for 10 years, and designated sub-station interconnection rights.",
    contentAr: "صُممت هذه المبادرة الثنائية لسد العجز الكهربائي، وتغطي حقلين للطاقة الشمسية مزودين بأنظمة التتبع ومستودعات تخزين طاقة بسعة ٣٠٠ ميغاواط/ساعة. يستفيد الشركاء من التخليص الجمركي الفوري في سفوان، والإعفاء الضريبي لمدة ١٠ سنوات، وربط مجاني بمحطات التحويل الرئيسية.",
    contentZh: "该中伊双边倡议旨在彻底解决南部电网赤字，包含两座配备双轴跟踪支架及300兆瓦时先进储能系统的大型光伏园区。入驻中企将享受萨夫万口岸绿色通关协议、企业所得税前十年全免以及免收电网接入费等多项特权。",
    contentCkb: "ئەم پرۆژەیە بۆ چارەسەری کێشەی کارەبای باشوورە، بە بەکارهێنانی سیستەمی کۆکردنەوەی وزە بە قەبارەی ٣٠٠ مێگاوات/کاتژمێر، لەگەڵ لێخۆشبوونی باج بۆ ماوەی دە ساڵ.",
    category: "ENERGY",
    sector: "Renewable Energy & Storage",
    investmentValue: "$1.4 Billion",
    location: "Muthanna & Najaf Deserts",
    coverImage: "https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    order: 2,
    status: "OPEN",
    contactEmail: "renewables@iraqi-chineseagency.com"
  },
  {
    slug: "faw-port-logistics-freezone",
    titleEn: "Al-Faw Grand Port International Bonded Logistics & Free Zone Park",
    titleAr: "المنطقة اللوجستية الحرة والميناء الجاف الدولي في ميناء الفاو الكبير",
    titleZh: "大港法奥港国际综合保税物流园区与自由贸易特区",
    titleCkb: "ناوچەی ئازادی لۆجستی و بەندەری وشکانی لە بەندەری فاو-ی گەورە",
    summaryEn: "Development of automated dry-dock warehouses, multi-modal rail interchange terminals, and deepwater container yards connecting the Maritime Silk Road to the Dry Canal.",
    summaryAr: "تطوير مستودعات الحوض الجاف المؤتمتة، ومحطات التبادل السككي متعددة الوسائط، وساحات الحاويات العميقة لربط طريق الحرير البحري بالقناة الجافة.",
    summaryZh: "依托法奥深水大港核心港区，建设集自动化保税仓储、铁水联运枢纽站及超深水集装箱堆场于一体的陆海新通道战略枢纽。",
    summaryCkb: "پەرەپێدانی کۆگاکانی حەوزی وشک و وێستگەکانی هێڵی ئاسن بۆ بەستنەوەی ڕێگای ئاوریشمی دەریایی بە کەناڵی وشکانی.",
    contentEn: "The General Company for Ports of Iraq (GCPI) offers multi-year concession contracts for international logistics operators to build bonded freight stations, cold-storage logistics chains, and container inspection gantries. The zone provides corporate zero-tariff status on raw re-exports, zero municipal fees for 15 years, and dedicated maritime berths constructed to 19.5m draft standards.",
    contentAr: "تطرح الشركة العامة لموانئ العراق عقود امتياز طويلة الأجل للمشغلين اللوجستيين لتشييد محطات الشحن الجمركي، وسلاسل التبريد، وبوابات فحص الحاويات. توفر المنطقة صفة الإعفاء الجمركي الكامل للمواد المعاد تصديرها، وإعفاء من الرسوم البلدية لمدة ١٥ عاماً، وأرصفة بعمق ١٩.٥ متراً.",
    contentZh: "伊拉克国家港务局（GCPI）面向具备实力的国际物流运营商推出特许经营合约，涵盖综合保税货运站、医药冷链枢纽及集装箱智能安检系统建设。特区享有转口贸易完全免税、前15年市政收费豁免，并直接配套吃水深度达19.5米的世界级深水集装箱泊位。",
    contentCkb: "کۆمپانیای گشتی بەندەرەکانی عێراق گرێبەستی درێژخایەن پێشکەش دەکات بۆ دروستکردنی ناوچەی گومرگی و کۆگای ساردکەرەوە بە بەخشینی باج لە باجی شارەوانی بۆ ١٥ ساڵ.",
    category: "INFRASTRUCTURE",
    sector: "Maritime Logistics & Free Zones",
    investmentValue: "$850 Million",
    location: "Al-Faw Peninsula, Basra",
    coverImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    order: 3,
    status: "OPEN",
    contactEmail: "fawlogistics@iraqi-chineseagency.com"
  },
  {
    slug: "tigris-drip-irrigation-agritech",
    titleEn: "Tigris Basin High-Efficiency Precision Agritech & Drip Irrigation",
    titleAr: "مشروع التقنيات الزراعية الحديثة والري بالتنقيط عالي الكفاءة في حوض دجلة",
    titleZh: "底格里斯河流域现代节水精准农业与智慧滴灌技术转移基地",
    titleCkb: "پڕۆژەی تەکنەلۆجیای نوێی کشتوکاڵی و ئاودێری دڵۆپەیی لە حەوزی دیجلە",
    summaryEn: "Modernizing cereal and high-yield crop cultivation across 80,000 dunams in Wasit and Dhi Qar utilizing Chinese low-pressure automated drip equipment and drought-resistant seeds.",
    summaryAr: "تحديث زراعة الحبوب والمحاصيل عالية الإنتاجية على مساحة ٨٠ ألف دونم في واسط وذي قار بالاعتماد على تقنيات الري الذكية والبذور المقاومة للجفاف.",
    summaryZh: "在瓦西特省和济加尔省8万杜纳姆良田推广应用中国先进微压精准水肥一体化滴灌系统及耐旱高产种业技术。",
    summaryCkb: "نوێکردنەوەی کەرتی کشتوکاڵی لەسەر ڕووبەری ٨٠ هەزار دۆنم لە واست و زیقار بە بەکارهێنانی سیستەمی ئاودێری پێشکەوتوو و تۆوی بەهێز.",
    contentEn: "In partnership with the Iraqi Supreme Agricultural Committee, this initiative grants 25-year leaseholds on agricultural state lands at nominal rates. Chinese agricultural equipment manufacturers are offered long-term off-take agreements by the Ministry of Trade for wheat and grain production, alongside guaranteed water discharge allocations from modern reservoir off-takes.",
    contentAr: "بالشراكة مع اللجنة الزراعية العليا، يمنح المشروع عقود إيجار لمدة ٢٥ عاماً على الأراضي الزراعية بأسعار رمزية. يحصل مصنعو المعدات الزراعية على عقود شراء حكومية طويلة الأجل لمحاصيل الحنطة، مع ضمان حصص مائية مقننة من السدود والخزانات الحديثة.",
    contentZh: "项目与伊拉克最高农业委员会联合开展，为投资主体提供25年期象征性地租的国有农业用地租赁权。伊拉克贸易部为生产的小麦及优质经济作物提供全额主权兜底收购协议，并由水资源部为智慧灌溉示范区提供排灌水源保障。",
    contentCkb: "بە هاوبەشی لەگەڵ لیژنەی باڵای کشتوکاڵ، زەوی کشتوکاڵی بۆ ٢٥ ساڵ بە نرخی ڕەمزی دابین دەکرێت، لەگەڵ گرێبەستی کڕینەوەی بەرهەم لەلایەن وەزارەتی بازرگانییەوە.",
    category: "AGRICULTURE",
    sector: "Precision Agronomy & Water Conservation",
    investmentValue: "$320 Million",
    location: "Wasit & Dhi Qar Governorates",
    coverImage: "https://images.unsplash.com/photo-1592417817098-8f3d6eb22509?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    order: 4,
    status: "OPEN",
    contactEmail: "agritech@iraqi-chineseagency.com"
  },
  {
    slug: "baghdad-erbil-fiber-datacenter",
    titleEn: "Baghdad-Kirkuk-Erbil Sovereign Terrestrial Fiber & Cloud Datacenter Backbone",
    titleAr: "العمود الفقري للألياف الضوئية ومراكز البيانات السحابية بين بغداد وكركوك وأربيل",
    titleZh: "巴格达-基尔库克-埃尔比勒国家级陆基光缆干线与主权云数据中心",
    titleCkb: "هێڵی سەرەکی فایبەر ئۆپتیک و سەنتەری داتای هەوری لە نێوان بەغدا، کەرکووک و هەولێر",
    summaryEn: "Deployment of 1,200 km dual-redundant buried fiber optic corridors and twin Tier-III sovereign data facilities in Baghdad and Erbil to support e-governance and bilateral digital clearing.",
    summaryAr: "مد ١٢٠٠ كم من كابلات الألياف الضوئية المزدوجة وإنشاء مركزي بيانات سياديين من المستوى الثالث في بغداد وأربيل لدعم الحوكمة الإلكترونية والمقاصة الرقمية.",
    summaryZh: "敷设1200公里高冗余埋地干线光缆，并在巴格达与埃尔比勒建设两座国际Tier-III级高可用主权数据中心，全方位支撑电子政务与双边数字清算网络。",
    summaryCkb: "ڕاکێشانی ١٢٠٠ کم کەیبڵی فایبەر ئۆپتیک و دروستکردنی دوو سەنتەری داتای پێشکەوتوو لە بەغدا و هەولێر بۆ خزمەتگوزاری دیجیتاڵی.",
    contentEn: "The Communications and Media Commission (CMC) and KRG Department of Information Technology provide unified sovereign concessions for fiber right-of-way alongside major highway corridors. Investors gain dark-fiber leasing exclusivity to telecom carriers and public ministries, backed by a 100% tax exemption on data hardware imports under Iraq Investment Law.",
    contentAr: "توفر هيئة الإعلام والاتصالات ودائرة تكنولوجيا المعلومات في إقليم كوردستان امتيازات موحدة لمد الألياف على امتداد الطرق السريعة. يحصل المستثمرون على حقوق تأجير حصرية لشركات الاتصالات والوزارات، مع إعفاء جمركي وضريبي كامل بنسبة ١٠٠٪ على خوادم ومعدات البيانات.",
    contentZh: "伊拉克通信与媒体委员会（CMC）及库区政府信息技术部联合授予沿国家高速公路干线的独家光缆管廊通行权。投资财团将获得向各大电信运营商及政府部门租赁裸光纤的独家特许权，同时享受服务器及通信设备进口全额免税待遇。",
    contentCkb: "دەستەی ڕاگەیاندن و گەیاندن و فەرمانگەی تەکنەلۆجیای زانیاری هەرێم مافی بەکارهێنانی ڕێگاکان دەبەخشن بۆ ڕاکێشانی هێڵەکان لەگەڵ بەخشینی تەواوی باج لەسەر ئامێرەکان.",
    category: "TECHNOLOGY",
    sector: "Cloud Infrastructure & 5G Grids",
    investmentValue: "$450 Million",
    location: "Federal Iraq & Kurdistan Region",
    coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    order: 5,
    status: "OPEN",
    contactEmail: "telecom@iraqi-chineseagency.com"
  },
  {
    slug: "kurdistan-mineral-industrial-park",
    titleEn: "Kurdistan Regional Mineral Extraction & Structural Metallurgy Park",
    titleAr: "مجمع استخراج المعادن والصناعات المعدنية الإنشائية في إقليم كوردستان",
    titleZh: "库尔德斯坦矿产资源高效开采与重型建材冶金工业园",
    titleCkb: "شارۆچکەی پیشەسازی دەرهێنانی کانزاکان و کانزا بیناسازییەکان لە هەرێمی كوردستان",
    summaryEn: "Large-scale limestone, gypsum, and structural steel manufacturing facilities situated under KRG Investment Law No. 4 with full 10-year tax exemptions and dedicated electrical grid tie-ins.",
    summaryAr: "منشآت لتصنيع الحجر الجيري والجبس والحديد الإنشائي بموجب قانون استثمار كوردستان رقم ٤ مع إعفاء ضريبي شامل لـ ١٠ سنوات وربط كهربائي صناعي مباشر.",
    summaryZh: "依托库尔德斯坦丰富的高品位石灰石与铁矿资源，依照库区第4号投资法建设现代化绿色建材与建筑钢材冶金产业园，享受10年全面免税及工业用电专线保障。",
    summaryCkb: "دامەزراندنی کارگەکانی بەردی گەچ و چیمەنتۆ و ئاسن بەپێی یاسای وەبەرهێنانی ژمارە ٤ی هەرێمی کوردستان بە لێخۆشبوونی تەواوی باج بۆ دە ساڵ.",
    contentEn: "Licensed by the KRG Board of Investment, the park covers 300 hectares near major transport axes connecting Erbil and Sulaymaniyah to central Iraq. Foreign enterprises enjoy 100% foreign ownership rights, sovereign leasehold protection, and direct export permits for building materials needed in national reconstruction programs.",
    contentAr: "مرخص من قبل هيئة استثمار كوردستان بمساحة ٣٠٠ هكتار بالقرب من المحاور الرابطة بين أربيل والسليمانية ووسط العراق. تتمتع الشركات الأجنبية بملكية بنسبة ١٠٠٪، وحماية سيادية لعقود الإيجار، وتصاريح تصدير وتوريد لمواد البناء المخصصة لإعادة الإعمار.",
    contentZh: "该产业园获得库区投资委员会全面特许批文，占地300公顷，扼守连接埃尔比勒、苏莱曼尼亚通往伊拉克中部平原的核心货运走廊。外资企业享有100%全资控股权、主权级租赁权益保护，并直通国家重建采购计划的建材直供采购通道。",
    contentCkb: "مۆڵەتدراوە لەلایەن دەستەی وەبەرهێنانی هەرێمی کوردستان لەسەر ڕووبەری ٣٠٠ هێکتار لە نێوان هەولێر و سلێمانی، بە مافی ١٠٠٪ خاوەندارێتی بۆ بیانییەکان.",
    category: "INDUSTRIAL_ZONES",
    sector: "Metallurgy & Building Materials",
    investmentValue: "$580 Million",
    location: "Sulaymaniyah & Erbil Governorates",
    coverImage: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    order: 6,
    status: "OPEN",
    contactEmail: "industrial@iraqi-chineseagency.com"
  },
  {
    slug: "bilateral-customs-legal-advisory",
    titleEn: "Bilateral Legal Advisory, Customs Exemption & Sovereign Treaty Desk",
    titleAr: "المكتب الاستشاري القانوني الثنائي للإعفاءات الجمركية والامتثال للمعاهدات السيادية",
    titleZh: "中伊双边商事法律顾问、海关免税政策与主权条约专属服务台",
    titleCkb: "دەفتەری ڕاوێژکاری یاسایی دووقۆڵی، لێخۆشبوونی گومرگی و پەیماننامە سیادییەکان",
    summaryEn: "Dedicated corporate retainer and compliance service guiding Chinese and international corporations through Investment Law No. 13 certifications, tax holidays, and bilateral dispute arbitration.",
    summaryAr: "خدمات استشارية ومتابعة للمؤسسات الصينية والدولية للحصول على شهادات قانون الاستثمار رقم ١٣، والإعفاءات الضريبية، والتحكيم التجاري الثنائي.",
    summaryZh: "为中资企业量身打造的常年投资法律合规与通关便利顾问服务，全程代办第13号投资法资质认证、免税批文、海关绿通核准及双边商事仲裁支持。",
    summaryCkb: "خزمەتگوزاری یاسایی و ڕاوێژکاری بۆ کۆمپانیا بیانی و چینییەکان بۆ وەرگرتنی لێخۆشبوونی باج بەپێی یاسای ژمارە ١٣ و چارەسەری ناکۆکییە بازرگانییەکان.",
    contentEn: "Administered directly by senior bilateral legal counsel accredited in Baghdad and Beijing, this desk handles certificate of investment issuance from the National Investment Commission (NIC), customs bond releases at Umm Qasr, and bilateral currency conversion guarantees. Available on retainers for state enterprises and private chambers of commerce.",
    contentAr: "يُدار المكتب مباشرة من قبل مستشارين قانونيين معتمدين في بغداد وبكين، ويتولى استخراج إجازات الاستثمار من الهيئة الوطنية للاستثمار (NIC)، والإفراج الجمركي في أم قصر، وضمانات تسوية العملات. متاح للشركات الحكومية وغرف التجارة.",
    contentZh: "由常驻巴格达与北京的资深双边涉外法务团队联合主理，直接协助企业高效申办伊拉克国家投资委员会（NIC）主权投资执照、乌姆盖斯尔港海关保函快速解押以及本币清算资金结算路径合规核验。支持大型央国企与民营商会按年委托签约。",
    contentCkb: "لەلایەن پارێزەران و پسپۆڕانی باوەڕپێکراو لە بەغدا و پەکین بەڕێوەدەبرێت، بۆ دەرکردنی مۆڵەتی دەستەی نیشتمانی وەبەرهێنان (NIC) و پاکتاوی گومرگی لە ئوم قەسر.",
    category: "LEGAL_ADVISORY",
    sector: "Trade Treaty Compliance & Tariff Immunities",
    investmentValue: "Institutional Retainer",
    location: "Baghdad / Beijing Bilateral Chambers",
    coverImage: "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1200&q=80",
    featured: false,
    order: 7,
    status: "ACTIVE",
    contactEmail: "legal@iraqi-chineseagency.com"
  },
  {
    slug: "rmb-iqd-trade-financing-facility",
    titleEn: "Bilateral RMB / IQD Sovereign Currency Settlement & Letter of Credit Facility",
    titleAr: "تسهيلات المقاصة المباشرة باليوان والدينار وخطابات الاعتماد المستندية الثنائية",
    titleZh: "中伊本币直接结算专项通道与跨境信用证融资便利化机制",
    titleCkb: "ئاسانکاری پاکتاوی دراوی یوان / دینار و نامەی متمانەی بانکی (LC)",
    summaryEn: "Direct bilateral clearing infrastructure bypassing third-party clearing currencies for heavy industrial machinery, energy EPC contracts, and raw agricultural imports.",
    summaryAr: "بنية تحتية للمقاصة الثنائية المباشرة لتجاوز العملات الوسيطة في تمويل المعدات الصناعية الثقيلة وعقود الطاقة والتوريدات الاستراتيجية.",
    summaryZh: "依托伊拉克中央银行与中国主要国有商业银行建立的主权直通清算架构，全面免除第三方货币对冲磨损，为大型工程总包与大宗进出口提供极速信用证开立服务。",
    summaryCkb: "ژێرخانی پاکتاوی ڕاستەوخۆ بەبێ دراوە ناوبەندەکان بۆ کڕینی ئامێرە قورسە پیشەسازییەکان و گرێبەستەکانی وزە بە یوان و دینار.",
    contentEn: "Under the supervision of the Central Bank of Iraq and Chinese correspondent partner banks, this financing desk offers issuance of RMB-denominated Letters of Credit (LC), structured supply-chain factoring, and sovereign escrow accounts. Over 35% of bilateral trade volume is supported with reduced transactional overhead and guaranteed settlement execution in under 24 hours.",
    contentAr: "تحت إشراف البنك المركزي العراقي والبنوك الصينية الشريكة، يقدم هذا المكتب إصدار خطابات اعتماد باليوان، وتمويل سلاسل الإمداد، وحسابات الضمان السيادية. يضمن تسوية أكثر من ٣٥٪ من التجارة الثنائية بكلفة منخفضة وتنفيذ خلال أقل من ٢٤ ساعة.",
    contentZh: "在伊拉克中央银行与中国大型战略商业银行监管框架下，本业务专柜提供人民币计价即期/远期信用证开立、供应链应收账款保理及主权托管账户管理。全面支持双边贸易直接结算，显著降低综合财务手续费，并实现24小时内极速双向资金清算交割。",
    contentCkb: "لەژێر چاودێری بانکی ناوەندی عێراق و بانکە هاوبەشە چینییەکان، دەرکردنی نامەی متمانە بە یوان و پاراستنی سەرمایە دابین دەکات بە جێبەجێکردن لە کەمتر لە ٢٤ کاتژمێردا.",
    category: "FINANCIAL_SERVICES",
    sector: "Cross-Border Settlement & Trade Finance",
    investmentValue: "Multi-Tier Sovereign Facility",
    location: "Central Bank of Iraq / PBOC Corridors",
    coverImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80",
    featured: true,
    order: 8,
    status: "ACTIVE",
    contactEmail: "finance@iraqi-chineseagency.com"
  }
];

export async function seedBusinessOpportunities() {
  try {
    const count = await prisma.businessOpportunity.count();
    if (count >= INITIAL_BUSINESS_OPPORTUNITIES.length) {
      return;
    }

    console.log("🏢 Seeding ICA Business Opportunities (8 bilateral projects)...");
    for (const item of INITIAL_BUSINESS_OPPORTUNITIES) {
      await prisma.businessOpportunity.upsert({
        where: { slug: item.slug },
        update: item,
        create: item,
      });
    }
    console.log("✅ ICA Business Opportunities successfully seeded.");
  } catch (error) {
    console.error("⚠️ Error seeding business opportunities:", error);
  }
}
