import { prisma } from './db.js';

export async function seedMarketData() {
  console.log('📈 Seeding/Updating market indices & China/HK stock data...');

  const initialItems = [
    // --- TOP CHINA INDICES ---
    {
      symbol: 'SSE',
      name: 'Shanghai Composite',
      nameZh: '上证综合指数',
      nameAr: 'مؤشر شنغهاي المركب',
      category: 'INDEX',
      price: 3058.20,
      change: 14.85,
      changePercent: 0.49,
      volume: '342.5B CNY',
      high: 3072.10,
      low: 3040.50,
      open: 3045.00,
      currency: 'CNY',
      marketCap: '48.2T CNY',
      peRatio: 13.8,
    },
    {
      symbol: 'SZSE',
      name: 'Shenzhen Component',
      nameZh: '深证成份指数',
      nameAr: 'مؤشر شينزن المركب',
      category: 'INDEX',
      price: 9485.60,
      change: 62.30,
      changePercent: 0.66,
      volume: '418.0B CNY',
      high: 9530.00,
      low: 9420.00,
      open: 9435.00,
      currency: 'CNY',
      marketCap: '32.1T CNY',
      peRatio: 21.4,
    },
    {
      symbol: 'CSI300',
      name: 'CSI 300 Index',
      nameZh: '沪深300指数',
      nameAr: 'مؤشر سي إس آي 300',
      category: 'INDEX',
      price: 3568.40,
      change: 21.10,
      changePercent: 0.59,
      volume: '215.8B CNY',
      high: 3590.00,
      low: 3545.00,
      open: 3550.00,
      currency: 'CNY',
      marketCap: '38.5T CNY',
      peRatio: 12.1,
    },
    {
      symbol: 'STAR50',
      name: 'SSE STAR 50',
      nameZh: '科创50指数',
      nameAr: 'مؤشر كوتشوانغ 50',
      category: 'INDEX',
      price: 782.30,
      change: -4.12,
      changePercent: -0.52,
      volume: '68.2B CNY',
      high: 790.10,
      low: 775.20,
      open: 788.00,
      currency: 'CNY',
      marketCap: '5.8T CNY',
      peRatio: 38.6,
    },

    // --- TOP HONG KONG INDICES ---
    {
      symbol: 'HSI',
      name: 'Hang Seng Index',
      nameZh: '香港恒生指数',
      nameAr: 'مؤشر هانغ سينغ - هونغ كونغ',
      category: 'INDEX',
      price: 17842.10,
      change: 215.40,
      changePercent: 1.22,
      volume: '118.5B HKD',
      high: 17950.00,
      low: 17720.00,
      open: 17680.00,
      currency: 'HKD',
      marketCap: '31.4T HKD',
      peRatio: 9.8,
    },
    {
      symbol: 'HSTECH',
      name: 'Hang Seng Tech',
      nameZh: '恒生科技指数',
      nameAr: 'مؤشر هانغ سينغ للتكنولوجيا',
      category: 'INDEX',
      price: 3655.80,
      change: 78.20,
      changePercent: 2.18,
      volume: '42.1B HKD',
      high: 3710.00,
      low: 3610.00,
      open: 3590.00,
      currency: 'HKD',
      marketCap: '12.8T HKD',
      peRatio: 26.5,
    },
    {
      symbol: 'HSCEI',
      name: 'Hang Seng China Ent.',
      nameZh: '国企指数(H股)',
      nameAr: 'مؤشر الشركات الصينية - هونغ كونغ',
      category: 'INDEX',
      price: 6320.15,
      change: 84.60,
      changePercent: 1.36,
      volume: '58.4B HKD',
      high: 6380.00,
      low: 6280.00,
      open: 6250.00,
      currency: 'HKD',
      marketCap: '22.1T HKD',
      peRatio: 8.2,
    },

    // --- TOP CHINA & HONG KONG STOCKS ---
    {
      symbol: '0700.HK',
      name: 'Tencent Holdings',
      nameZh: '腾讯控股',
      nameAr: 'تينسنت القابضة',
      category: 'HK_STOCK',
      price: 385.60,
      change: 8.20,
      changePercent: 2.17,
      volume: '14.8M',
      high: 389.00,
      low: 378.20,
      open: 380.00,
      currency: 'HKD',
      marketCap: '3.55T HKD',
      peRatio: 22.4,
    },
    {
      symbol: '9988.HK',
      name: 'Alibaba Group',
      nameZh: '阿里巴巴集团',
      nameAr: 'مجموعة علي بابا',
      category: 'HK_STOCK',
      price: 79.80,
      change: 1.95,
      changePercent: 2.51,
      volume: '38.2M',
      high: 80.50,
      low: 78.10,
      open: 78.30,
      currency: 'HKD',
      marketCap: '1.52T HKD',
      peRatio: 16.8,
    },
    {
      symbol: '0857.HK',
      name: 'PetroChina (HK)',
      nameZh: '中国石油股份',
      nameAr: 'بتروتشاينا (هونغ كونغ)',
      category: 'HK_STOCK',
      price: 7.25,
      change: 0.14,
      changePercent: 1.97,
      volume: '82.4M',
      high: 7.32,
      low: 7.12,
      open: 7.15,
      currency: 'HKD',
      marketCap: '1.33T HKD',
      peRatio: 7.2,
    },
    {
      symbol: '0883.HK',
      name: 'CNOOC Limited',
      nameZh: '中国海洋石油',
      nameAr: 'سينوك النفطية البحرية',
      category: 'HK_STOCK',
      price: 20.15,
      change: 0.45,
      changePercent: 2.28,
      volume: '45.1M',
      high: 20.40,
      low: 19.70,
      open: 19.80,
      currency: 'HKD',
      marketCap: '958B HKD',
      peRatio: 6.5,
    },
    {
      symbol: '1211.HK',
      name: 'BYD Company',
      nameZh: '比亚迪股份',
      nameAr: 'شركة بي واي دي للسيارات',
      category: 'HK_STOCK',
      price: 238.40,
      change: 6.80,
      changePercent: 2.94,
      volume: '8.9M',
      high: 241.00,
      low: 232.00,
      open: 233.00,
      currency: 'HKD',
      marketCap: '693B HKD',
      peRatio: 24.1,
    },
    {
      symbol: '3690.HK',
      name: 'Meituan',
      nameZh: '美团',
      nameAr: 'ميتوان للتكنولوجيا',
      category: 'HK_STOCK',
      price: 121.50,
      change: -1.20,
      changePercent: -0.98,
      volume: '22.4M',
      high: 124.20,
      low: 120.10,
      open: 123.00,
      currency: 'HKD',
      marketCap: '758B HKD',
      peRatio: 28.3,
    },
    {
      symbol: '1810.HK',
      name: 'Xiaomi Corp',
      nameZh: '小米集团',
      nameAr: 'شاومي للتكنولوجيا',
      category: 'HK_STOCK',
      price: 18.90,
      change: 0.62,
      changePercent: 3.39,
      volume: '54.2M',
      high: 19.10,
      low: 18.30,
      open: 18.35,
      currency: 'HKD',
      marketCap: '472B HKD',
      peRatio: 21.0,
    },
    {
      symbol: '1398.HK',
      name: 'ICBC Bank',
      nameZh: '中国工商银行',
      nameAr: 'البنك الصناعي والتجاري الصيني',
      category: 'HK_STOCK',
      price: 4.58,
      change: 0.04,
      changePercent: 0.88,
      volume: '112.0M',
      high: 4.61,
      low: 4.52,
      open: 4.54,
      currency: 'HKD',
      marketCap: '1.63T HKD',
      peRatio: 4.8,
    },
    {
      symbol: '0941.HK',
      name: 'China Mobile',
      nameZh: '中国移动',
      nameAr: 'تشاينا موبايل الاتصالات',
      category: 'HK_STOCK',
      price: 75.30,
      change: 0.80,
      changePercent: 1.07,
      volume: '18.5M',
      high: 75.80,
      low: 74.50,
      open: 74.60,
      currency: 'HKD',
      marketCap: '1.61T HKD',
      peRatio: 10.5,
    },
    {
      symbol: '600519.SH',
      name: 'Kweichow Moutai',
      nameZh: '贵州茅台',
      nameAr: 'كويتشو موتاي',
      category: 'CHINA_STOCK',
      price: 1685.00,
      change: 12.50,
      changePercent: 0.75,
      volume: '2.8M',
      high: 1698.00,
      low: 1670.00,
      open: 1675.00,
      currency: 'CNY',
      marketCap: '2.12T CNY',
      peRatio: 27.5,
    },
    {
      symbol: '601857.SH',
      name: 'PetroChina A-Share',
      nameZh: '中国石油(A股)',
      nameAr: 'بتروتشاينا - أسهم أ',
      category: 'CHINA_STOCK',
      price: 9.92,
      change: 0.18,
      changePercent: 1.85,
      volume: '68.5M',
      high: 10.05,
      low: 9.75,
      open: 9.78,
      currency: 'CNY',
      marketCap: '1.81T CNY',
      peRatio: 8.1,
    },

    // --- COMMODITIES & IRAQ MARKETS & FOREX ---
    {
      symbol: 'ISX60',
      name: 'Iraq Stock Exchange ISX60',
      nameZh: '伊拉克证券交易所ISX60',
      nameAr: 'مؤشر سوق العراق للأوراق المالية ISX60',
      category: 'INDEX',
      price: 988.50,
      change: 6.20,
      changePercent: 0.63,
      volume: '4.8B IQD',
      high: 992.00,
      low: 982.10,
      open: 983.00,
      currency: 'IQD',
      marketCap: '14.2T IQD',
      peRatio: 11.2,
    },
    {
      symbol: 'BRENT',
      name: 'Brent Crude Oil',
      nameZh: '布伦特原油',
      nameAr: 'خام برنت النفطي',
      category: 'COMMODITY',
      price: 83.15,
      change: 1.25,
      changePercent: 1.53,
      volume: '284K Contracts',
      high: 83.80,
      low: 81.90,
      open: 82.00,
      currency: 'USD',
      marketCap: '-',
      peRatio: 0,
    },
    {
      symbol: 'SHANGHAI_OIL',
      name: 'INE Shanghai Crude',
      nameZh: '上海原油期货',
      nameAr: 'نفط شنغهاي الخياري',
      category: 'COMMODITY',
      price: 615.40,
      change: 8.60,
      changePercent: 1.42,
      volume: '142K Contracts',
      high: 620.00,
      low: 608.20,
      open: 609.00,
      currency: 'CNY',
      marketCap: '-',
      peRatio: 0,
    },
    {
      symbol: 'GOLD',
      name: 'Gold Spot (XAU/USD)',
      nameZh: '现货黄金',
      nameAr: 'أسعار الذهب الفوري',
      category: 'COMMODITY',
      price: 2392.10,
      change: -6.40,
      changePercent: -0.27,
      volume: '195K Oz',
      high: 2405.00,
      low: 2385.00,
      open: 2398.50,
      currency: 'USD',
      marketCap: '-',
      peRatio: 0,
    },
    {
      symbol: 'CNY_USD',
      name: 'USD / CNY Exchange',
      nameZh: '美元/人民币',
      nameAr: 'سعر الدولار / اليوان الصيني',
      category: 'FOREX',
      price: 7.2340,
      change: -0.0085,
      changePercent: -0.12,
      volume: 'Forex Direct',
      high: 7.2480,
      low: 7.2290,
      open: 7.2420,
      currency: 'CNY',
      marketCap: '-',
      peRatio: 0,
    },
    {
      symbol: 'IQD_USD',
      name: 'USD / IQD Official Rate',
      nameZh: '美元/伊拉克第纳尔',
      nameAr: 'سعر الدولار / الدينار العراقي',
      category: 'FOREX',
      price: 1310.00,
      change: 0.00,
      changePercent: 0.00,
      volume: 'CBI Rate',
      high: 1310.00,
      low: 1310.00,
      open: 1310.00,
      currency: 'IQD',
      marketCap: '-',
      peRatio: 0,
    }
  ];

  for (const item of initialItems) {
    await prisma.marketData.upsert({
      where: { symbol: item.symbol },
      update: {
        name: item.name,
        nameZh: item.nameZh,
        nameAr: item.nameAr,
        category: item.category,
        price: item.price,
        change: item.change,
        changePercent: item.changePercent,
        volume: item.volume,
        high: item.high,
        low: item.low,
        open: item.open,
        currency: item.currency,
        marketCap: item.marketCap,
        peRatio: item.peRatio,
      },
      create: item,
    });
  }

  console.log(`✅ Successfully seeded ${initialItems.length} market indices and stock items.`);
}
