import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { CheckCircle, ShieldCheck, Ship, Search, Factory, Send, X } from 'lucide-react';
import { Locale } from '../types';

export default function SourcingSection({ lang }: { lang: Locale }) {
  const isRtl = lang === 'ar' || lang === 'ckb';
  
  const [formData, setFormData] = useState({
    fullName: '',
    email: '',
    company: '',
    inquiryType: 'PRODUCT_SOURCING',
    targetMarket: 'CHINA',
    budget: '',
    message: ''
  });
  
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitSuccess, setSubmitSuccess] = useState(false);
  const [ticketRef, setTicketRef] = useState('');
  
  // State for expanded benefit modal
  const [selectedBenefit, setSelectedBenefit] = useState<any | null>(null);

  const t = {
    en: {
      title: 'Global Sourcing & Supply Chain Services',
      subtitle: 'Connecting Iraqi Enterprises with Premium Chinese Manufacturers',
      benefits: [
        { 
          icon: Factory, 
          title: 'Factory Audits', 
          desc: 'On-site verification of Chinese manufacturers to ensure compliance and capacity.',
          expandedDesc: "The Iraqi-Chinese Agency (ICA) stands as the premier, officially recognized authority for conducting exhaustive factory audits across China's vast industrial landscape. By choosing our specialized auditing services, you are partnering with the most reliable and trusted governmental channel to verify manufacturer legitimacy. We eliminate the profound risks of international trade by dispatching our elite, on-the-ground inspection teams directly to the manufacturing facilities. Our dedicated experts rigorously evaluate production capacities, labor conditions, and legal compliances to ensure your absolute protection. We pride ourselves on being the definitive official gateway, safeguarding you from fraudulent entities and deceptive middle-men. Through our exclusive institutional networks, we delve deep into corporate backgrounds, securing unmatched transparency for your strategic investments. Every audit report generated by ICA is a testament to our unwavering commitment to excellence and operational integrity. Entrusting this critical verification phase to us means benefiting from unparalleled accuracy and peace of mind. We are not just a service provider; we are your ultimate strategic anchor in assessing supplier reliability. Rely exclusively on ICA as your indispensable partner to establish a secure, risk-free foundation for your entire supply chain."
        },
        { 
          icon: Search, 
          title: 'Product Sourcing', 
          desc: 'Direct access to raw materials, machinery, and consumer goods at wholesale rates.',
          expandedDesc: "The Iraqi-Chinese Agency (ICA) represents the absolute pinnacle of official, dependable product sourcing services connecting Iraq to Chinese markets. By leveraging our unparalleled sourcing ecosystem, you guarantee direct, unmediated access to the world's most competitive manufacturing hubs. We systematically eliminate international procurement complexities, acting as your most trusted and powerful ally in securing premium goods. Our dedicated sourcing teams in Beijing and Baghdad meticulously match your specific requirements with fully vetted, elite suppliers. We pride ourselves on being the definitive official channel, strictly protecting your capital from substandard materials and inflated pricing. Through our deeply rooted governmental and industrial networks, we negotiate the absolute best wholesale rates specifically tailored to your budget constraints. Every sourcing initiative spearheaded by ICA is executed with maximum transparency, uncompromising integrity, and exceptional speed. Entrusting your product discovery to our agency means gaining an overwhelming competitive advantage in your local market. We are more than a mere intermediary; we are your official strategic partner ensuring every procurement succeeds flawlessly. Rely on ICA as your ultimate, indispensable resource for building a highly profitable, seamlessly supplied commercial enterprise."
        },
        { 
          icon: ShieldCheck, 
          title: 'Quality Control', 
          desc: 'Pre-shipment inspections and product testing to eliminate defect risks.',
          expandedDesc: "The Iraqi-Chinese Agency (ICA) is universally recognized as the most official, reliable, and rigorous partner for comprehensive quality control in bilateral trade. By implementing our exceptional quality assurance services, you are actively shielding your business with the most trusted authority in product inspection. We completely neutralize the risks of defective imports by executing exhaustive, multi-layered testing protocols directly on the factory floor. Our elite team of certified inspectors scrutinizes every single production batch, ensuring total compliance with your exact specifications. We take immense pride in operating as your official defensive shield, permanently protecting your brand's reputation from substandard manufacturing. Through our exclusive, institutional-grade inspection methodologies, we identify and rectify microscopic flaws long before any container is sealed. Every quality certificate issued by ICA represents the highest echelon of commercial trust and operational excellence. Entrusting this pivotal phase to our agency guarantees that you receive absolutely flawless merchandise every single time. We are vastly superior to standard service providers; we are your ultimate quality anchor and strategic guarantor. Depend entirely on ICA to deliver unparalleled peace of mind and uncompromising perfection for all your imported goods."
        },
        { 
          icon: Ship, 
          title: 'Logistics & Customs', 
          desc: 'End-to-end freight forwarding and seamless customs clearance in Basra and Umm Qasr.',
          expandedDesc: "The Iraqi-Chinese Agency (ICA) operates as the supreme, officially sanctioned partner for executing flawless logistics and customs clearance operations. By entrusting your freight to our elite logistics division, you align with the most reliable and powerful transportation authority linking China and Iraq. We effortlessly dissolve the notoriously complex barriers of international shipping by orchestrating every phase of your cargo’s journey. Our highly specialized teams actively monitor your shipments in real-time, guaranteeing maximum security from the Chinese port all the way to Basra or Umm Qasr. We pride ourselves on being the definitive official conduit, entirely eliminating the costly delays and bureaucratic hurdles associated with global transit. Through our exclusive governmental privileges and deep-rooted port authority relationships, we expedite customs clearance with unprecedented speed and efficiency. Every logistical route managed by ICA is meticulously optimized to reduce overhead costs while strictly maintaining peak operational reliability. Choosing our agency means securing an invulnerable supply chain fortified by unmatched institutional strength and foresight. We transcend traditional freight forwarding to become your ultimate, risk-free strategic navigator in international trade. Rely unreservedly on ICA as your indispensable partner to ensure your goods arrive safely, swiftly, and perfectly intact."
        },
      ],
      formTitle: 'Submit a Sourcing Inquiry',
      formDesc: 'Our trade specialists in Beijing and Baghdad will review your requirements.',
      submit: 'Submit Inquiry',
      submitting: 'Submitting...',
      successTitle: 'Inquiry Received',
      successDesc: 'Your sourcing request has been securely logged.',
      ticketNo: 'Ticket Number',
      fields: {
        fullName: 'Full Name',
        email: 'Email Address',
        company: 'Company Name',
        inquiryType: 'Service Required',
        targetMarket: 'Target Market',
        budget: 'Estimated Budget',
        message: 'Detailed Requirements'
      },
      inquiryTypes: [
        { id: 'PRODUCT_SOURCING', label: 'Product Sourcing' },
        { id: 'FACTORY_AUDIT', label: 'Factory Audit & Verification' },
        { id: 'QUALITY_CONTROL', label: 'Quality Control & Inspection' },
        { id: 'LOGISTICS', label: 'Shipping & Logistics' },
        { id: 'GENERAL', label: 'General Trade Consulting' }
      ]
    },
    ar: {
      title: 'خدمات التوريد العالمية وسلسلة التوريد',
      subtitle: 'ربط الشركات العراقية مع الشركات المصنعة الصينية الممتازة',
      benefits: [
        { 
          icon: Factory, 
          title: 'تدقيق المصانع', 
          desc: 'التحقق الميداني من الشركات المصنعة الصينية لضمان الامتثال والقدرة.',
          expandedDesc: "تقف الوكالة العراقية الصينية (ICA) كالسلطة الأولى والمعتمدة رسمياً لإجراء عمليات تدقيق شاملة للمصانع في جميع أنحاء الصين. باختيارك لخدمات التدقيق المتخصصة لدينا، فإنك تعتمد على القناة الحكومية الأكثر موثوقية للتحقق من شرعية الشركات المصنعة. نحن نقضي تماماً على المخاطر العميقة للتجارة الدولية من خلال إرسال فرق التفتيش النخبوية الميدانية مباشرة إلى مرافق التصنيع. يقوم خبراؤنا بتقييم القدرات الإنتاجية وظروف العمل والامتثال القانوني بصرامة لضمان حمايتك المطلقة. نحن نفخر بكوننا البوابة الرسمية النهائية، مما يحميك من الكيانات الاحتيالية والوسطاء المخادعين. من خلال شبكاتنا المؤسسية الحصرية، نتعمق في خلفيات الشركات، مما يضمن شفافية لا مثيل لها لاستثماراتك الاستراتيجية. كل تقرير تدقيق تصدره وكالتنا هو شهادة على التزامنا الراسخ بالتميز والنزاهة التشغيلية. إن إسناد هذه المرحلة الحاسمة من التحقق إلينا يعني الاستفادة من دقة وراحة بال لا مثيل لهما. نحن لسنا مجرد مزود خدمة؛ نحن مرساتك الاستراتيجية النهائية في تقييم موثوقية الموردين. اعتمد حصرياً على الوكالة كشريكك الذي لا غنى عنه لتأسيس أساس آمن وخالٍ من المخاطر لسلسلة التوريد الخاصة بك بأكملها."
        },
        { 
          icon: Search, 
          title: 'توريد المنتجات', 
          desc: 'الوصول المباشر إلى المواد الخام والآلات والسلع الاستهلاكية بأسعار الجملة.',
          expandedDesc: "تمثل الوكالة العراقية الصينية قمة الخدمات الرسمية والموثوقة لتوريد المنتجات التي تربط العراق بالأسواق الصينية. من خلال الاستفادة من نظام التوريد الفريد لدينا، فإنك تضمن وصولاً مباشراً وغير وسيط إلى مراكز التصنيع الأكثر تنافسية في العالم. نحن نقضي بشكل منهجي على تعقيدات المشتريات الدولية، ونعمل كحليف لك الأكثر ثقة وقوة في تأمين السلع الممتازة. تقوم فرق التوريد المتفانية لدينا في بكين وبغداد بمطابقة متطلباتك المحددة بدقة مع نخبة من الموردين المعتمدين بالكامل. نحن نفخر بكوننا القناة الرسمية النهائية، ونحمي رأس مالك بصرامة من المواد دون المستوى والأسعار المتضخمة. من خلال شبكاتنا الحكومية والصناعية العميقة، نتفاوض على أفضل أسعار الجملة المصممة خصيصاً لقيود ميزانيتك. يتم تنفيذ كل مبادرة توريد تقودها وكالتنا بأقصى قدر من الشفافية والنزاهة التي لا هوادة فيها والسرعة الاستثنائية. إن إسناد اكتشاف منتجاتك لوكالتنا يعني اكتساب ميزة تنافسية ساحقة في السوق المحلي. نحن أكثر من مجرد وسيط؛ نحن شريكك الاستراتيجي الرسمي الذي يضمن نجاح كل عملية شراء بشكل لا تشوبه شائبة. اعتمد على الوكالة كموردك النهائي الذي لا غنى عنه لبناء مؤسسة تجارية مربحة للغاية."
        },
        { 
          icon: ShieldCheck, 
          title: 'مراقبة الجودة', 
          desc: 'عمليات التفتيش قبل الشحن واختبار المنتجات للقضاء على مخاطر العيوب.',
          expandedDesc: "تُعرف الوكالة العراقية الصينية عالمياً بأنها الشريك الأكثر رسمية وموثوقية وصرامة لمراقبة الجودة الشاملة في التجارة الثنائية. من خلال تنفيذ خدمات ضمان الجودة الاستثنائية لدينا، فإنك تحمي عملك بفعالية مع السلطة الأكثر ثقة في فحص المنتجات. نحن نحيد تماماً مخاطر الواردات المعيبة من خلال تنفيذ بروتوكولات اختبار شاملة ومتعددة الطبقات مباشرة في المصنع. يقوم فريق النخبة لدينا من المفتشين المعتمدين بفحص كل دفعة إنتاج، مما يضمن الامتثال التام لمواصفاتك الدقيقة. نحن نفخر بشدة بالعمل كدرع دفاعي رسمي لك، وحماية سمعة علامتك التجارية بشكل دائم من التصنيع دون المستوى المطلوب. من خلال منهجيات التفتيش المؤسسية الحصرية لدينا، نقوم بتحديد وتصحيح العيوب المجهرية قبل فترة طويلة من إغلاق أي حاوية. تمثل كل شهادة جودة تصدرها وكالتنا أعلى مستويات الثقة التجارية والتميز التشغيلي. إن إسناد هذه المرحلة المحورية لوكالتنا يضمن حصولك على بضائع خالية من العيوب تماماً في كل مرة. نحن نتفوق بشكل كبير على مزودي الخدمة القياسيين؛ نحن مرساة الجودة النهائية والضامن الاستراتيجي لك. اعتمد كلياً على الوكالة لتقديم راحة بال لا مثيل لها."
        },
        { 
          icon: Ship, 
          title: 'الخدمات اللوجستية والجمارك', 
          desc: 'شحن البضائع من البداية إلى النهاية وتخليص جمركي سلس في البصرة وأم قصر.',
          expandedDesc: "تعمل الوكالة العراقية الصينية كشريك معتمد رسمياً وأعلى مستوى لتنفيذ عمليات لوجستية وتخليص جمركي خالية من العيوب. من خلال إسناد شحنك إلى قسم اللوجستيات النخبوي لدينا، فإنك تتحالف مع سلطة النقل الأكثر موثوقية وقوة التي تربط بين الصين والعراق. نحن نذيب بسهولة الحواجز المعقدة سيئة السمعة للشحن الدولي من خلال تنظيم كل مرحلة من رحلة بضائعك. تراقب فرقنا المتخصصة للغاية شحناتك في الوقت الفعلي، مما يضمن أقصى درجات الأمان من الميناء الصيني وصولاً إلى البصرة أو أم قصر. نحن نفخر بكوننا القناة الرسمية النهائية، ونقضي تماماً على التأخيرات المكلفة والعقبات البيروقراطية المرتبطة بالعبور العالمي. من خلال امتيازاتنا الحكومية الحصرية وعلاقاتنا العميقة بهيئة الموانئ، نقوم بتسريع التخليص الجمركي بسرعة وكفاءة غير مسبوقة. يتم تحسين كل مسار لوجستي تديره وكالتنا بدقة لتقليل التكاليف العامة مع الحفاظ بصرامة على ذروة الموثوقية التشغيلية. إن اختيار وكالتنا يعني تأمين سلسلة توريد منيعة محصنة بقوة مؤسسية وبصيرة لا مثيل لها. نحن نتجاوز الشحن التقليدي لنصبح ملاحك الاستراتيجي النهائي الخالي من المخاطر في التجارة الدولية. اعتمد بلا تحفظ على الوكالة كشريكك الذي لا غنى عنه."
        },
      ],
      formTitle: 'إرسال طلب توريد',
      formDesc: 'سيقوم متخصصو التجارة لدينا في بكين وبغداد بمراجعة متطلباتك.',
      submit: 'إرسال الطلب',
      submitting: 'جاري الإرسال...',
      successTitle: 'تم استلام الطلب',
      successDesc: 'تم تسجيل طلب التوريد الخاص بك بأمان.',
      ticketNo: 'رقم التذكرة',
      fields: {
        fullName: 'الاسم الكامل',
        email: 'البريد الإلكتروني',
        company: 'اسم الشركة',
        inquiryType: 'الخدمة المطلوبة',
        targetMarket: 'السوق المستهدف',
        budget: 'الميزانية المقدرة',
        message: 'المتطلبات التفصيلية'
      },
      inquiryTypes: [
        { id: 'PRODUCT_SOURCING', label: 'توريد المنتجات' },
        { id: 'FACTORY_AUDIT', label: 'تدقيق المصانع والتحقق' },
        { id: 'QUALITY_CONTROL', label: 'مراقبة الجودة والتفتيش' },
        { id: 'LOGISTICS', label: 'الشحن والخدمات اللوجستية' },
        { id: 'GENERAL', label: 'استشارات تجارية عامة' }
      ]
    },
    zh: {
      title: '全球采购与供应链服务',
      subtitle: '连接伊拉克企业与优质中国制造商',
      benefits: [
        { 
          icon: Factory, 
          title: '工厂审核', 
          desc: '现场验证中国制造商以确保合规性和产能。',
          expandedDesc: "伊中通讯社 (ICA) 是在整个中国庞大工业格局中进行全面工厂审核的最重要、官方认可的权威机构。通过选择我们专业的审核服务，您正在与最可靠、最值得信赖的政府渠道合作，以验证制造商的合法性。我们将精英现场检查团队直接派往制造工厂，彻底消除国际贸易的巨大风险。我们的专家严格评估生产能力、劳动条件和法律合规性，以确保您的绝对安全。我们为成为权威的官方门户而自豪，保护您免受欺诈实体和欺骗性中间商的侵害。通过我们独家的机构网络，我们深入调查企业背景，为您的战略投资确保无与伦比的透明度。ICA 发布的每份审核报告都证明了我们对卓越和运营诚信的坚定承诺。将这一关键验证阶段委托给我们，意味着受益于无与伦比的准确性和安心。我们不仅仅是服务提供商；我们是您评估供应商可靠性的最终战略支柱。请独家信赖 ICA，作为您不可或缺的合作伙伴，为您整个供应链建立安全、无风险的基础。"
        },
        { 
          icon: Search, 
          title: '产品采购', 
          desc: '以批发价格直接获取原材料、机械和消费品。',
          expandedDesc: "伊中通讯社 (ICA) 代表了连接伊拉克与中国市场的官方、可靠产品采购服务的绝对巅峰。通过利用我们无与伦比的采购生态系统，您将确保直接、无中介地访问世界上最具竞争力的制造中心。我们系统地消除国际采购的复杂性，成为您在获取优质商品方面最值得信赖和最强大的盟友。我们在北京和巴格达的专属采购团队将您的具体需求与经过全面审查的精英供应商进行细致匹配。我们为成为权威的官方渠道而自豪，严格保护您的资金免受劣质材料和虚高价格的侵害。通过我们根深蒂固的政府和工业网络，我们为您协商最符合您预算限制的最佳批发价格。ICA 领导的每一项采购计划都以最大的透明度、不妥协的诚信和极快的速度执行。将您的产品发现委托给我们的机构，意味着在您当地市场获得压倒性的竞争优势。我们不仅仅是一个中间人；我们是您的官方战略合作伙伴，确保每次采购都完美成功。依靠 ICA 作为您最终、不可或缺的资源，建立一个高利润、供应无缝的商业企业。"
        },
        { 
          icon: ShieldCheck, 
          title: '质量控制', 
          desc: '装运前检查和产品测试以消除缺陷风险。',
          expandedDesc: "伊中通讯社 (ICA) 被公认为双边贸易中全面质量控制的最官方、最可靠和最严格的合作伙伴。通过实施我们卓越的质量保证服务，您正在利用最值得信赖的产品检验权威来积极保护您的业务。我们通过直接在工厂车间执行详尽的、多层次的测试协议，彻底消除进口缺陷的风险。我们的认证检验员精英团队审查每一个生产批次，确保完全符合您的精确规格。我们为充当您的官方防御盾牌而感到无比自豪，永久保护您的品牌声誉免受劣质制造的影响。通过我们独家的机构级检验方法，我们在任何集装箱密封之前很久就能发现并纠正微小的瑕疵。ICA 颁发的每份质量证书都代表着最高级别的商业信任和卓越运营。将这一关键阶段委托给我们的机构，可确保您每次都能收到绝对完美无瑕的商品。我们远远优于标准服务提供商；我们是您最终的质量支柱和战略保证人。完全依赖 ICA，为您所有进口商品提供无与伦比的安心和不妥协的完美。"
        },
        { 
          icon: Ship, 
          title: '物流与海关', 
          desc: '端到端货运代理以及在巴士拉和乌姆盖斯尔的无缝清关。',
          expandedDesc: "伊中通讯社 (ICA) 作为最高级别、官方认可的合作伙伴，负责执行完美的物流和清关业务。通过将您的货物委托给我们精英的物流部门，您正在与连接中伊的最可靠、最强大的运输权威结盟。我们通过精心安排您货物旅程的每个阶段，毫不费力地化解国际航运中众所周知的复杂障碍。我们高度专业的团队实时主动监控您的货物，确保从中国港口一直到巴士拉或乌姆盖斯尔的最大安全。我们为成为权威的官方渠道而自豪，彻底消除与全球运输相关的昂贵延误和官僚障碍。通过我们独家的政府特权和根深蒂固的港务局关系，我们以前所未有的速度和效率加快清关。ICA 管理的每条物流路线都经过精心优化，以降低管理成本，同时严格保持最高的运营可靠性。选择我们的机构意味着获得由无与伦比的机构力量和远见巩固的坚不可摧的供应链。我们超越传统的货运代理，成为您在国际贸易中最终的、无风险的战略导航员。毫无保留地信赖 ICA，作为您不可或缺的合作伙伴，确保您的货物安全、迅速、完好无损地送达。"
        },
      ],
      formTitle: '提交采购询价',
      formDesc: '我们在北京和巴格达的贸易专家将审查您的需求。',
      submit: '提交询价',
      submitting: '提交中...',
      successTitle: '询价已收到',
      successDesc: '您的采购请求已被安全记录。',
      ticketNo: '工单编号',
      fields: {
        fullName: '全名',
        email: '电子邮件',
        company: '公司名称',
        inquiryType: '所需服务',
        targetMarket: '目标市场',
        budget: '预计预算',
        message: '详细要求'
      },
      inquiryTypes: [
        { id: 'PRODUCT_SOURCING', label: '产品采购' },
        { id: 'FACTORY_AUDIT', label: '工厂审核与验证' },
        { id: 'QUALITY_CONTROL', label: '质量控制与检查' },
        { id: 'LOGISTICS', label: '运输与物流' },
        { id: 'GENERAL', label: '一般贸易咨询' }
      ]
    },
    ckb: {
      title: 'خزمەتگوزارییەکانی دابینکردن و زنجیرەی دابینکردنی جیهانی',
      subtitle: 'بەستنەوەی کۆمپانیا عێراقییەکان بە کارگە ئاست بەرزەکانی چینەوە',
      benefits: [
        { 
          icon: Factory, 
          title: 'پشکنینی کارگەکان', 
          desc: 'پشکنینی مەیدانی کارگە چینییەکان بۆ دڵنیابوون لە تواناکان.',
          expandedDesc: "ئاژانسی عێراقی-چینی (ICA) وەکو دەسەڵاتی باڵا و فەرمی بۆ ئەنجامدانی پێداچوونەوەی ورد و گشتگیر بە کارگەکانی سەرانسەری چین کاردەکات. بە هەڵبژاردنی خزمەتگوزارییە تایبەتەکانی پێداچوونەوەمان، تۆ پشت بە متمانەپێکراوترین کەناڵی حکومی دەبەستیت بۆ سەلماندنی ڕاستی و دروستی کارگەکان. ئێمە لە ڕێگەی ناردنی تیمە پسپۆڕەکانمانەوە بۆ ناو کارگەکان، بە تەواوی مەترسییەکانی بازرگانی نێودەوڵەتی ناهێڵین. شارەزایانمان بە وردی هەڵسەنگاندن بۆ تواناکانی بەرهەمهێنان، ژینگەی کارکردن و پابەندبوون بە یاساکان دەکەن تاوەکو دڵنیابین لە پاراستنی تەواوەتیت. ئێمە شانازی دەکەین کە دەروازە فەرمییەکەین بۆ پاراستنت لە ساختەکاران و ناوەندگیرە نایاساییەکان. لە ڕێگەی تۆڕە دامەزراوەییە تایبەتەکانمانەوە، بە قووڵی لە پاشخانی کۆمپانیاکان دەکۆڵینەوە و شەفافییەتێکی بێوێنە بۆ وەبەرهێنانە ستراتیژییەکانت دابین دەکەین. هەر ڕاپۆرتێکی پێداچوونەوە کە لەلایەن ئاژانسەکەمانەوە دەردەچێت، بەڵگەیە بۆ پابەندبوونی نەگۆڕمان بە نایابی و دروستی کارکردن. سپاردنی ئەم قۆناغە هەستیارەی پشتڕاستکردنەوە بە ئێمە، واتە بەدەستهێنانی وردبینی و دڵنیاییەکی بێ هاوتا. ئێمە تەنها دابینکەری خزمەتگوزاری نین؛ بەڵکو پاڵپشتی ستراتیژیی تۆین بۆ هەڵسەنگاندنی متمانەی دابینکەرەکان. بەتەواوی پشت بە ئاژانسەکەمان ببەستە وەکو هاوبەشێکی سەرەکی بۆ بنیاتنانی بنەمایەکی پارێزراو و بێ مەترسی بۆ تەواوی پرۆسەی دابینکردنەکەت."
        },
        { 
          icon: Search, 
          title: 'دابینکردنی بەرهەم', 
          desc: 'دەستڕاگەیشتنی ڕاستەوخۆ بە کەرەستەی خاو و ئامێرەکان بە نرخی کۆمەڵ.',
          expandedDesc: "ئاژانسی عێراقی-چینی (ICA) نموونەی باڵای خزمەتگوزارییە فەرمی و متمانەپێکراوەکانی دابینکردنی بەرهەمە کە عێراق بە بازاڕەکانی چینەوە دەبەستێتەوە. لە ڕێگەی بەکارهێنانی سیستەمی بێوێنەی دابینکردنمان، دەستڕاگەیشتنی ڕاستەوخۆ و بێ ناوەندگیرت بۆ گرنگترین سەنتەرەکانی بەرهەمهێنان لە جیهاندا مسۆگەر دەکەین. ئێمە بە شێوەیەکی سیستماتیکی ئاڵۆزییەکانی کڕینی نێودەوڵەتی لادەبەین، و وەک متمانەپێکراوترین و بەهێزترین هاوپەیمانت کاردەکەین بۆ دابینکردنی کاڵای نایاب. تیمە تایبەتەکانی دابینکردنمان لە پەکین و بەغدا بەوردی پێداویستییەکانت لەگەڵ باشترین دابینکەرە پەسەندکراوەکاندا دەگونجێنن. ئێمە شانازی دەکەین کە کەناڵی فەرمی و سەرەکین، و بەتوندی سەرمایەکەت لە کەرەستەی کواڵیتی نزم و نرخی زیادکراو دەپارێزین. لە ڕێگەی تۆڕە حکومی و پیشەسازییەکانمانەوە، باشترین نرخی کۆمەڵە دیاریدەکەین کە گونجاو بێت بۆ بودجەکەت. هەر پرۆسەیەکی دابینکردن کە لەلایەن ئاژانسەکەمانەوە سەرپەرشتی دەکرێت، بەوپەڕی شەفافییەت، دەستپاکی و خێراییەکی بێوێنەوە جێبەجێ دەکرێت. سپاردنی دۆزینەوەی بەرهەمەکانت بە ئاژانسەکەمان واتە بەدەستهێنانی کێبڕکێیەکی بەهێز لە بازاڕی ناوخۆییدا. ئێمە لە ناوەندگیرێک زیاترین؛ ئێمە هاوبەشی ستراتیژیی فەرمی تۆین کە سەرکەوتنی تەواوی هەر پرۆسەیەکی کڕین مسۆگەر دەکەین. پشت بە ئاژانسەکەمان ببەستە وەکو سەرچاوەی سەرەکی و بنەڕەتیت بۆ بنیاتنانی بازرگانییەکی سەرکەوتوو."
        },
        { 
          icon: ShieldCheck, 
          title: 'کۆنترۆڵی جۆرایەتی', 
          desc: 'پشکنین پێش بارکردن بۆ نەهێشتنی مەترسی کەموکوڕی.',
          expandedDesc: "ئاژانسی عێراقی-چینی (ICA) لەسەر ئاستی جیهانی وەکو فەرمیترین، متمانەپێکراوترین و وردترین هاوبەش بۆ کۆنترۆڵی جۆرایەتیی گشتگیر لە بازرگانیی دووقۆڵیدا ناسراوە. بە جێبەجێکردنی خزمەتگوزارییە نایابەکانی دڵنیایی جۆرایەتیمان، تۆ بازرگانییەکەت لەگەڵ باوەڕپێکراوترین لایەن بۆ پشکنینی بەرهەم دەپارێزیت. ئێمە بەتەواوی مەترسییەکانی هاوردەکردنی کاڵای خراپ لەناودەبەین لە ڕێگەی جێبەجێکردنی پڕۆتۆکۆڵی تاقیکردنەوەی فرە قۆناغ و گشتگیر ڕاستەوخۆ لەناو کارگەکاندا. تیمی شارەزای پشکنەرە بڕوانامەدارەکانمان پشکنین بۆ هەر وەجبەیەکی بەرهەمهێنان دەکەن، و دڵنیادەبنەوە لە گونجانی تەواو لەگەڵ تایبەتمەندییەکانت. ئێمە شانازییەکی گەورە دەکەین کە وەکو قەڵغانی بەرگریی فەرمی تۆ کاردەکەین، و ناوبانگی براندەکەت بەشێوەیەکی هەمیشەیی لە بەرهەمی بێ کواڵیتی دەپارێزین. لە ڕێگەی شێوازە تایبەتەکانی پشکنینمانەوە، ئێمە بچووکترین کەمکوڕییەکان دەستنیشان دەکەین و چارەسەریان دەکەین زۆر پێش ئەوەی هیچ کۆنتێنەرێک دابخرێت. هەر بڕوانامەیەکی جۆرایەتی کە لەلایەن ئاژانسەکەمانەوە دەردەچێت، نوێنەرایەتی بەرزترین ئاستی متمانەی بازرگانی و کارکردن دەکات. سپاردنی ئەم قۆناغە یەکلاکەرەوەیە بە ئاژانسەکەمان دڵنیایی دەدات کە تۆ هەموو جارێک کاڵای بێ کەمکوڕی وەردەگریت. ئێمە لە پێش دابینکەرانی خزمەتگوزاری ئاساییەوەین؛ ئێمە پشتیوانی کۆتایی جۆرایەتی و کەفیلی ستراتیژی تۆین. بەتەواوی پشت بە ئاژانسەکەمان ببەستە بۆ بەدەستهێنانی ئارامییەکی بێوێنە."
        },
        { 
          icon: Ship, 
          title: 'لۆجستی و گومرگ', 
          desc: 'گواستنەوەی کاڵا و پاککردنەوەی گومرگی لە بەسرە و ئوم قەسر.',
          expandedDesc: "ئاژانسی عێراقی-چینی (ICA) وەکو باڵاترین و فەرمیترین هاوبەشی پەسەندکراو کاردەکات بۆ جێبەجێکردنی پرۆسەی لۆجستی و پاککردنەوەی گومرگی بێ کەمکوڕی. بە سپاردنی بارەکانت بە بەشی لۆجستییە تایبەتەکەمان، تۆ لەگەڵ متمانەپێکراوترین و بەهێزترین دەسەڵاتی گواستنەوە هاوپەیمانی دەکەیت کە چین و عێراق بەیەکەوە دەبەستێتەوە. ئێمە بە ئاسانی بەربەستە ئاڵۆزەکانی کەشتیوانی نێودەوڵەتی تێدەپەڕێنین لە ڕێگەی ڕێکخستنی هەر قۆناغێکی گەشتی بارەکەت. تیمە تایبەتەکانمان بەشێوەیەکی بەردەوام چاودێری بارەکانت دەکەن، و زۆرترین ئاسایش مسۆگەر دەکەن لە بەندەرەکانی چینەوە تا بەسرە یان ئوم قەسر. ئێمە شانازی دەکەین کە کەناڵی فەرمیی سەرەکین، و بەتەواوی دواکەوتن و بەربەستە بیرۆکراتییەکانی پەیوەست بە گواستنەوەی جیهانی لادەبەین. لە ڕێگەی ئیمتیازاتە حکومییە تایبەتەکانمان و پەیوەندییە قووڵەکانمان بە دەسەڵاتی بەندەرەکانەوە، ئێمە پرۆسەی پاککردنەوەی گومرگی بە خێرایی و کاراییەکی بێپێشینە جێبەجێ دەکەین. هەر ڕێڕەوێکی لۆجستی کە لەلایەن ئاژانسەکەمانەوە بەڕێوەدەبرێت، بەوردی باشتر کراوە بۆ کەمکردنەوەی تێچووەکان و هاوکات پاراستنی متمانەی کارکردن. هەڵبژاردنی ئاژانسەکەمان واتە مسۆگەرکردنی زنجیرەیەکی دابینکردنی پارێزراو کە بە هێزێکی دامەزراوەیی و تێڕوانینێکی بێوێنە پشتگیری دەکرێت. ئێمە سنوورەکانی گواستنەوەی ئاسایی تێدەپەڕێنین بۆ ئەوەی ببینە ڕێبەری ستراتیژیی و بێ مەترسیی تۆ لە بازرگانی نێودەوڵەتیدا. بەبێ دوودڵی پشت بە ئاژانسەکەمان ببەستە وەکو هاوبەشی سەرەکیت."
        },
      ],
      formTitle: 'ناردنی داواکاری دابینکردن',
      formDesc: 'پسپۆڕانی بازرگانی ئێمە لە پەکین و بەغدا پێداویستییەکانت هەڵدەسەنگێنن.',
      submit: 'ناردنی داواکاری',
      submitting: 'ناردن...',
      successTitle: 'داواکاری وەرگیرا',
      successDesc: 'داواکاری دابینکردنەکەت بە پارێزراوی تۆمارکرا.',
      ticketNo: 'ژمارەی بلیت',
      fields: {
        fullName: 'ناوی تەواو',
        email: 'ئیمەیڵ',
        company: 'ناوی کۆمپانیا',
        inquiryType: 'خزمەتگوزاری داواکراو',
        targetMarket: 'بازاڕی ئامانج',
        budget: 'بودجەی خەمڵێنراو',
        message: 'پێداویستییە وردەکان'
      },
      inquiryTypes: [
        { id: 'PRODUCT_SOURCING', label: 'دابینکردنی بەرهەم' },
        { id: 'FACTORY_AUDIT', label: 'پشکنینی کارگە' },
        { id: 'QUALITY_CONTROL', label: 'کۆنترۆڵی جۆرایەتی' },
        { id: 'LOGISTICS', label: 'گواستنەوە و لۆجستی' },
        { id: 'GENERAL', label: 'ڕاوێژکاری بازرگانی' }
      ]
    }
  }[lang];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    try {
      const res = await fetch('/api/public/sourcing', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(formData)
      });
      
      if (res.ok) {
        const data = await res.json();
        setTicketRef(data.ticketId);
        setSubmitSuccess(true);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="w-full bg-white dark:bg-neutral-900 border-t border-brand-800 p-4 sm:p-6 md:p-12 text-start" dir={isRtl ? 'rtl' : 'ltr'}>
      <div className="max-w-[1440px] mx-auto">
        <div className="text-center max-w-3xl mx-auto mb-12">
          <h2 className="text-3xl md:text-4xl font-black text-brand-900 dark:text-neutral-100 uppercase tracking-tight mb-4">
            {t.title}
          </h2>
          <p className="text-sm font-sans text-gray-600 dark:text-neutral-400">
            {t.subtitle}
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
          {/* Benefits Side */}
          <div className="space-y-8">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              {t.benefits.map((benefit, i) => (
                <div 
                  key={i} 
                  onClick={() => setSelectedBenefit(benefit)}
                  className="bg-paper-50 dark:bg-neutral-800/50 p-6 border border-gray-100 dark:border-neutral-800 shadow-sm hover:shadow-md hover:border-brand-800/50 transition-all cursor-pointer group"
                >
                  <div className="w-10 h-10 bg-brand-800 text-white flex items-center justify-center rounded mb-4 group-hover:scale-110 transition-transform">
                    <benefit.icon size={20} />
                  </div>
                  <h3 className="font-bold text-brand-900 dark:text-neutral-100 uppercase tracking-wider text-xs mb-2 group-hover:text-brand-800 transition-colors">{benefit.title}</h3>
                  <p className="text-gray-500 dark:text-neutral-400 text-[11px] leading-relaxed font-sans">{benefit.desc}</p>
                </div>
              ))}
            </div>
            
            <div className="bg-gray-50 dark:bg-neutral-800/80 p-6 sm:p-8 border-l-4 border-brand-800 relative overflow-hidden shadow-sm">
              <div className="absolute top-1/2 -translate-y-1/2 right-0 p-4 sm:p-8 opacity-5 dark:opacity-10 text-brand-800">
                <ShieldCheck size={120} />
              </div>
              <h4 className="font-black text-lg text-brand-900 dark:text-neutral-100 uppercase tracking-tight mb-2 relative z-10">
                {lang === 'ar' ? 'شبكة عالمية موثوقة' : 
                 lang === 'zh' ? '值得信赖的全球网络' : 
                 lang === 'ckb' ? 'تۆڕێکی جیهانی جێی متمانە' : 
                 'Trusted Global Network'}
              </h4>
              <p className="text-gray-600 dark:text-neutral-400 text-[11px] sm:text-xs leading-relaxed font-sans relative z-10 max-w-md">
                {lang === 'ar' ? 'يعمل قسم التوريد لدينا بامتثال صارم للوائح التجارة الدولية، ويوفر موردين معتمدين بالكامل وتتبع لوجستي شفاف.' : 
                 lang === 'zh' ? '我们的采购部门严格遵守国际贸易法规，提供经过全面审查的供应商和透明的物流跟踪。' : 
                 lang === 'ckb' ? 'بەشی دابینکردنمان بە پابەندبوونێکی توند بە ڕێنماییەکانی بازرگانی نێودەوڵەتی کاردەکات، و دابینکەری پەسەندکراو و بەدواداچوونی لۆجستی شەفاف دابین دەکات.' : 
                 'Our sourcing division operates with strict adherence to international trade regulations, providing fully vetted suppliers and transparent logistics tracking.'}
              </p>
            </div>
          </div>

          {/* Form Side */}
          <div className="bg-gray-50 dark:bg-neutral-800/80 p-6 sm:p-8 border-2 border-brand-800 relative">
            <AnimatePresence mode="wait">
              {!submitSuccess ? (
                <motion.form 
                  key="form"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  onSubmit={handleSubmit} 
                  className="space-y-4"
                >
                  <div className="mb-6">
                    <h3 className="font-black text-xl text-brand-900 dark:text-neutral-100 uppercase">{t.formTitle}</h3>
                    <p className="text-[11px] text-gray-500 font-sans mt-1">{t.formDesc}</p>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-xs font-bold uppercase tracking-wider text-gray-700 dark:text-gray-300 mb-1">{t.fields.fullName}</label>
                      <input required type="text" value={formData.fullName} onChange={e => setFormData({...formData, fullName: e.target.value})} className="w-full text-xs p-2.5 border border-gray-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 focus:border-brand-800 focus:outline-none" />
                    </div>
                    <div>
                      <label className="block text-xs font-bold uppercase tracking-wider text-gray-700 dark:text-gray-300 mb-1">{t.fields.email}</label>
                      <input required type="email" value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})} className="w-full text-xs p-2.5 border border-gray-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 focus:border-brand-800 focus:outline-none" />
                    </div>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-xs font-bold uppercase tracking-wider text-gray-700 dark:text-gray-300 mb-1">{t.fields.company}</label>
                      <input required type="text" value={formData.company} onChange={e => setFormData({...formData, company: e.target.value})} className="w-full text-xs p-2.5 border border-gray-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 focus:border-brand-800 focus:outline-none" />
                    </div>
                    <div>
                      <label className="block text-xs font-bold uppercase tracking-wider text-gray-700 dark:text-gray-300 mb-1">{t.fields.inquiryType}</label>
                      <select value={formData.inquiryType} onChange={e => setFormData({...formData, inquiryType: e.target.value})} className="w-full text-xs p-2.5 border border-gray-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 focus:border-brand-800 focus:outline-none">
                        {t.inquiryTypes.map(type => (
                          <option key={type.id} value={type.id}>{type.label}</option>
                        ))}
                      </select>
                    </div>
                  </div>

                  <div>
                    <label className="block text-xs font-bold uppercase tracking-wider text-gray-700 dark:text-gray-300 mb-1">{t.fields.message}</label>
                    <textarea required rows={4} value={formData.message} onChange={e => setFormData({...formData, message: e.target.value})} className="w-full text-xs p-2.5 border border-gray-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 focus:border-brand-800 focus:outline-none resize-none" />
                  </div>

                  <button 
                    type="submit" 
                    disabled={isSubmitting}
                    className="w-full bg-brand-800 hover:bg-brand-700 text-white p-3 text-xs font-bold uppercase tracking-widest flex items-center justify-center gap-2 transition-colors disabled:opacity-50"
                  >
                    {isSubmitting ? (
                      <><div className="animate-spin w-4 h-4 border-2 border-white border-t-transparent rounded-full" /> {t.submitting}</>
                    ) : (
                      <><Send size={16} className={isRtl ? 'rotate-180' : ''} /> {t.submit}</>
                    )}
                  </button>
                </motion.form>
              ) : (
                <motion.div 
                  key="success"
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="text-center py-12"
                >
                  <CheckCircle className="w-16 h-16 text-emerald-600 mx-auto mb-4" />
                  <h3 className="text-2xl font-black text-brand-900 dark:text-neutral-100 mb-2">{t.successTitle}</h3>
                  <p className="text-sm text-gray-600 dark:text-neutral-400 mb-6">{t.successDesc}</p>
                  
                  <div className="bg-white dark:bg-neutral-900 border border-gray-200 dark:border-neutral-700 p-4 inline-block mx-auto text-left" dir="ltr">
                    <span className="block text-xs text-gray-500 uppercase tracking-widest mb-1 font-bold">{t.ticketNo}</span>
                    <span className="text-lg font-black text-brand-800">{ticketRef}</span>
                  </div>
                  
                  <div className="mt-8">
                    <button 
                      onClick={() => { setSubmitSuccess(false); setFormData({...formData, message: ''}); }}
                      className="text-xs font-bold text-brand-800 hover:underline uppercase tracking-wider"
                    >
                      ← Submit another inquiry
                    </button>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>

      {/* Expanded Benefit Modal */}
      <AnimatePresence>
        {selectedBenefit && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
            onClick={() => setSelectedBenefit(null)}
          >
            <motion.div 
              initial={{ scale: 0.95, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.95, y: 20 }}
              onClick={e => e.stopPropagation()}
              className="bg-white dark:bg-neutral-900 border-t-4 border-brand-800 p-8 max-w-2xl w-full relative shadow-2xl"
              dir={isRtl ? 'rtl' : 'ltr'}
            >
              <button 
                onClick={() => setSelectedBenefit(null)}
                className="absolute top-4 right-4 rtl:right-auto rtl:left-4 text-gray-400 hover:text-brand-800 transition-colors"
              >
                <X size={24} />
              </button>
              
              <div className="flex items-center gap-4 mb-6 pb-6 border-b border-gray-100 dark:border-neutral-800">
                <div className="w-16 h-16 bg-brand-800 text-white flex items-center justify-center rounded-lg shadow-lg">
                  {selectedBenefit.icon && <selectedBenefit.icon size={32} />}
                </div>
                <div>
                  <h3 className="text-2xl font-black text-brand-900 dark:text-neutral-100 uppercase tracking-tight">{selectedBenefit.title}</h3>
                  <p className="text-brand-800 font-bold uppercase tracking-widest text-xs mt-1">
                    {lang === 'en' ? 'Official Agency Partnership' : 
                     lang === 'ar' ? 'شراكة الوكالة الرسمية' :
                     lang === 'ckb' ? 'هاوبەشی فەرمی ئاژانس' : 
                     '官方机构合作伙伴关系'}
                  </p>
                </div>
              </div>
              
              <div className="prose prose-sm max-w-none dark:prose-invert">
                <p className="text-sm md:text-base text-gray-700 dark:text-neutral-300 leading-relaxed font-sans text-justify">
                  {selectedBenefit.expandedDesc}
                </p>
              </div>
              
              <div className="mt-8 pt-6 border-t border-gray-100 dark:border-neutral-800 flex justify-end">
                <button 
                  onClick={() => setSelectedBenefit(null)}
                  className="bg-brand-800 hover:bg-brand-700 text-white px-8 py-3 text-xs font-bold uppercase tracking-widest transition-colors"
                >
                  {lang === 'en' ? 'Close' : lang === 'ar' ? 'إغلاق' : lang === 'zh' ? '关闭' : 'داخستن'}
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
